apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "avengers-app.gateway" . }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.mediumTrust.ingressGateway.port }}
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.mediumTrust.hostname }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "avengers-app.virtualServiceName" . }}
spec:
  hosts:
    - {{ .Values.mediumTrust.hostname }}
  gateways:
    - {{ include "avengers-app.gateway" . }}
  http:
    - route:
        - destination:
            host: {{ include "avengers-app.host" . }}
            subset: avengersAppDestination
            port:
              number: {{ .Values.global.app.clusterIpPort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "avengers-app.destRule" . }}
spec:
  host: {{ include "avengers-app.host" . }}
  subsets:
    - name: avengersAppDestination
      labels:
        app.kuberentes.io/name: {{ include "avengers-app.name" . }}
