apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "avengers-app.gateway" . }}
  namespace: "mediumtrust"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: ISTIO_MUTUAL
      hosts:
        - "cr1-avengers-app.mediumtrust.svc.cluster.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "avengers-app.virtualServiceName" . }}
  namespace: "mediumtrust"
spec:
  hosts:
    - "cr1-avengers-app.mediumtrust.svc.cluster.local"
  gateways:
    - {{ include "avengers-app.gateway" . }}
  http:
    - match:
        - port: 443
      route:
        - destination:
            host: "cr1-avengers-app.mediumtrust.svc.cluster.local"
            port:
              number: 8081