apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "avengers-httpd.gateway" . }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "avengers-httpd.virtualServiceName" . }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "avengers-httpd.gateway" . }}
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: {{ include "avengers-httpd.host" . }}
            subset: avengersAppDestination
            port:
              number: {{ .Values.global.httpd.clusterIpPort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "avengers-httpd.destRule" . }}
spec:
  host: {{ include "avengers-httpd.host" . }}
  subsets:
    - name: avengersAppDestination
      labels:
        app.kubernetes.io/instance: "cr1"
        app.kuberentes.io/name: {{ include "avengers-httpd.name" . }}
