avengers-istio:
  lowTrust:
    hostname: "lowtrust.avengers.local"
    ingressGateway:
      tlsName: "default-lowtrust-avengers-local-credential"
      port: 443
  mediumTrust:
    hostname: "mediumtrust.avengers.local"
    ingressGateway:
      port: 445

avengers-httpd:
  proxy:
    app:
      host: "host.docker.internal"
      port: 80

global:
  app:
    clusterIpPort: 8081
    applicationPort: 8080
  httpd:
    clusterIpPort: 8070
    applicationPort: 7000
