avengers-istio:
  lowTrust:
    hostname: "lowtrust.avengers.local"
    ingressGateway:
      tlsName: "default-lowtrust-avengers-local-credential"
      port: 443
  mediumTrust:
    hostname: "mediumtrust.avengers.local"
    ingressGateway:
      tlsName: "default-mediumtrust-avengers-local-credential"
      port: 445

avengers-httpd:
  proxy:
    app:
      protocol: http
      host: "cr1-avengers-app.lowtrust.svc.cluster.local"
      port: 8081

global:
  app:
    clusterIpPort: 8081
    applicationPort: 8080
  httpd:
    clusterIpPort: 8070
    applicationPort: 7000
