apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "avengers-app.fullname" . }}
  namespace: "mediumtrust"
  labels:
    {{- include "avengers-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "avengers-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      namespace: "mediumtrust"
      labels:
        {{- include "avengers-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "avengers-app.serviceAccountName" . }}
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.global.app.applicationPort }}
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /avengers/index.html
              port: {{ .Values.global.app.applicationPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}