apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "avengers-app.fullname" . }}
  labels:
    {{- include "avengers-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "avengers-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "avengers-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "avengers-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: {{ .Values.global.app.applicationPort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.global.app.applicationPort }}
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /avengers/index.html
              port: {{ .Values.global.app.applicationPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}