apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "avengers-app.fullname" . }}
  namespace: "mediumtrust"
spec:
  podSelector:
    matchLabels:
      {{- include "avengers-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              istio: ingressgateway
      ports:
        - protocol: TCP
          port: {{ .Values.global.app.applicationPort }}
