apiVersion: v1
kind: Service
metadata:
  name: {{ include "avengers-app.fullname" . }}
  namespace: "mediumtrust"
  labels:
    {{- include "avengers-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: tcp
  selector:
    {{- include "avengers-app.selectorLabels" . | nindent 4 }}
