apiVersion: v1
kind: Service
metadata:
  name: {{ include "avengers-app.fullname" . }}
  labels:
    {{- include "avengers-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.app.clusterIpPort }}
      targetPort: {{ .Values.global.app.applicationPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "avengers-app.selectorLabels" . | nindent 4 }}
