apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "avengers-httpd.fullname" . }}
  namespace: "lowtrust"
spec:
  podSelector:
    matchLabels:
      {{- include "avengers-httpd.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: istio-internal
          podSelector:
            matchLabels:
              istio: ingressgateway
      ports:
        - protocol: TCP
          port: {{ .Values.global.httpd.applicationPort }}
