apiVersion: v1
kind: Service
metadata:
  name: {{ include "avengers-httpd.fullname" . }}
  namespace: "lowtrust"
  labels:
    {{- include "avengers-httpd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.httpd.clusterIpPort }}
      targetPort: {{ .Values.global.httpd.applicationPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "avengers-httpd.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: cr1-avengers-app
  namespace: "lowtrust"
spec:
  ports:
    - port: {{ .Values.global.app.clusterIpPort }}
      targetPort: {{ .Values.global.app.applicationPort }}
      protocol: TCP
      name: http
